apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-staging
  namespace: staging
  labels:
    app: wordpress
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      environment: staging
  template:
    metadata:
      labels:
        app: wordpress
        environment: staging
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql-staging"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-staging
                  key: password
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
          resources:  # Added resource requests and limits
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: wp-data
          persistentVolumeClaim:
            claimName: wp-pvc-staging
