apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-development
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      environment: development
  template:
    metadata:
      labels:
        app: wordpress
        environment: development
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-development
                  key: database_host
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-development
                  key: password
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html
          resources:  # Adding resource requests and limits
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:  # This section is moved inside the pod spec
        - name: wp-data
          persistentVolumeClaim:
            claimName: wp-pvc-development
