apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-production
  labels:
    environment: production
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/wp-production
