apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc-staging
  namespace: staging
  labels:
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      environment: staging
