apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc-production
  namespace: production
  labels:
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      environment: production
