apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-development
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: pv-development
