apiVersion: v1
kind: Service
metadata:
  name: wp-service-development
  namespace: development
  labels:
    app: wordpress
    environment: development
spec:
  type: NodePort
  selector:
    app: wordpress
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # NodePort range is 30000–32767
