apiVersion: v1
kind: Service
metadata:
  name: wp-service-staging
  namespace: staging
  labels:
    app: wordpress
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: wordpress
    environment: staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
