apiVersion: v1
kind: Service
metadata:
  name: wp-service-production
  namespace: production
  labels:
    app: wordpress
    environment: production
spec:
  type: NodePort
  selector:
    app: wordpress
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002 
