apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-production
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-production
  namespace: production
  labels:
    app: mysql
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      environment: production
  template:
    metadata:
      labels:
        app: mysql
        environment: production
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-production
                  key: password
            - name: MYSQL_DATABASE
              value: wordpress
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc-production
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-production
  namespace: production
spec:
  selector:
    app: mysql
    environment: production
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
